/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DashRouteImport } from './routes/dash'
import { Route as EvalClaimRouteImport } from './routes/eval-claim'
import { Route as FlyerRouteImport } from './routes/flyer'
import { Route as HodRouteImport } from './routes/hod'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as MskRouteImport } from './routes/msk'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SubClaimRouteImport } from './routes/sub-claim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalClaimRoute = EvalClaimRouteImport.update({
  id: '/eval-claim',
  path: '/eval-claim',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyerRoute = FlyerRouteImport.update({
  id: '/flyer',
  path: '/flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const HodRoute = HodRouteImport.update({
  id: '/hod',
  path: '/hod',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const MskRoute = MskRouteImport.update({
  id: '/msk',
  path: '/msk',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SubClaimRoute = SubClaimRouteImport.update({
  id: '/sub-claim',
  path: '/sub-claim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/building': typeof BuildingRoute
  '/daily': typeof DailyRoute
  '/dash': typeof DashRoute
  '/eval-claim': typeof EvalClaimRoute
  '/flyer': typeof FlyerRoute
  '/hod': typeof HodRoute
  '/issues': typeof IssuesRoute
  '/matrix': typeof MatrixRoute
  '/msk': typeof MskRoute
  '/office': typeof OfficeRoute
  '/papers': typeof PapersRoute
  '/pay': typeof PayRoute
  '/people': typeof PeopleRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/site': typeof SiteRoute
  '/sub-claim': typeof SubClaimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/building': typeof BuildingRoute
  '/daily': typeof DailyRoute
  '/dash': typeof DashRoute
  '/eval-claim': typeof EvalClaimRoute
  '/flyer': typeof FlyerRoute
  '/hod': typeof HodRoute
  '/issues': typeof IssuesRoute
  '/matrix': typeof MatrixRoute
  '/msk': typeof MskRoute
  '/office': typeof OfficeRoute
  '/papers': typeof PapersRoute
  '/pay': typeof PayRoute
  '/people': typeof PeopleRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/site': typeof SiteRoute
  '/sub-claim': typeof SubClaimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/building': typeof BuildingRoute
  '/daily': typeof DailyRoute
  '/dash': typeof DashRoute
  '/eval-claim': typeof EvalClaimRoute
  '/flyer': typeof FlyerRoute
  '/hod': typeof HodRoute
  '/issues': typeof IssuesRoute
  '/matrix': typeof MatrixRoute
  '/msk': typeof MskRoute
  '/office': typeof OfficeRoute
  '/papers': typeof PapersRoute
  '/pay': typeof PayRoute
  '/people': typeof PeopleRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/site': typeof SiteRoute
  '/sub-claim': typeof SubClaimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/building'
    | '/daily'
    | '/dash'
    | '/eval-claim'
    | '/flyer'
    | '/hod'
    | '/issues'
    | '/matrix'
    | '/msk'
    | '/office'
    | '/papers'
    | '/pay'
    | '/people'
    | '/plan'
    | '/progress'
    | '/site'
    | '/sub-claim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/building'
    | '/daily'
    | '/dash'
    | '/eval-claim'
    | '/flyer'
    | '/hod'
    | '/issues'
    | '/matrix'
    | '/msk'
    | '/office'
    | '/papers'
    | '/pay'
    | '/people'
    | '/plan'
    | '/progress'
    | '/site'
    | '/sub-claim'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/building'
    | '/daily'
    | '/dash'
    | '/eval-claim'
    | '/flyer'
    | '/hod'
    | '/issues'
    | '/matrix'
    | '/msk'
    | '/office'
    | '/papers'
    | '/pay'
    | '/people'
    | '/plan'
    | '/progress'
    | '/site'
    | '/sub-claim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  BuildingRoute: typeof BuildingRoute
  DailyRoute: typeof DailyRoute
  DashRoute: typeof DashRoute
  EvalClaimRoute: typeof EvalClaimRoute
  FlyerRoute: typeof FlyerRoute
  HodRoute: typeof HodRoute
  IssuesRoute: typeof IssuesRoute
  MatrixRoute: typeof MatrixRoute
  MskRoute: typeof MskRoute
  OfficeRoute: typeof OfficeRoute
  PapersRoute: typeof PapersRoute
  PayRoute: typeof PayRoute
  PeopleRoute: typeof PeopleRoute
  PlanRoute: typeof PlanRoute
  ProgressRoute: typeof ProgressRoute
  SiteRoute: typeof SiteRoute
  SubClaimRoute: typeof SubClaimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval-claim': {
      id: '/eval-claim'
      path: '/eval-claim'
      fullPath: '/eval-claim'
      preLoaderRoute: typeof EvalClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyer': {
      id: '/flyer'
      path: '/flyer'
      fullPath: '/flyer'
      preLoaderRoute: typeof FlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod': {
      id: '/hod'
      path: '/hod'
      fullPath: '/hod'
      preLoaderRoute: typeof HodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msk': {
      id: '/msk'
      path: '/msk'
      fullPath: '/msk'
      preLoaderRoute: typeof MskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-claim': {
      id: '/sub-claim'
      path: '/sub-claim'
      fullPath: '/sub-claim'
      preLoaderRoute: typeof SubClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  BuildingRoute: BuildingRoute,
  DailyRoute: DailyRoute,
  DashRoute: DashRoute,
  EvalClaimRoute: EvalClaimRoute,
  FlyerRoute: FlyerRoute,
  HodRoute: HodRoute,
  IssuesRoute: IssuesRoute,
  MatrixRoute: MatrixRoute,
  MskRoute: MskRoute,
  OfficeRoute: OfficeRoute,
  PapersRoute: PapersRoute,
  PayRoute: PayRoute,
  PeopleRoute: PeopleRoute,
  PlanRoute: PlanRoute,
  ProgressRoute: ProgressRoute,
  SiteRoute: SiteRoute,
  SubClaimRoute: SubClaimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
